[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indraGit = { id = "net.kyori.indra.git", version.ref = "indra" }
indraSpotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "3.0.2" }
modPublishPlugin = { id = "me.modmuss50.mod-publish-plugin", version = "1.0.0" }

[versions]
ktlint = "1.0.1"
indra = "4.0.0"

[libraries]
reflection-remapper = "xyz.jpenilla:reflection-remapper:0.1.3"
